#!/usr/bin/env bash

# Generate tags
docker tag "${DOCKER_REPO}:ubuntu-${TAG}" "${DOCKER_USERNAME}/${DOCKER_REPO}:ubuntu-${TAG}"

# Login to Docker Hub
echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

# Push the image and tags
docker push "${DOCKER_USERNAME}/${DOCKER_REPO}:ubuntu-${TAG}"

# Push groovy as latest
if [ "${TAG}" == "groovy" ]; then
    docker tag "${DOCKER_REPO}:ubuntu-${TAG}" "${DOCKER_USERNAME}/${DOCKER_REPO}:latest"
    docker push "${DOCKER_USERNAME}/${DOCKER_REPO}:latest"
fi
