#!/usr/bin/env bash

# Grab the base image and extract the Ubuntu version
docker pull "ubuntu:${TAG}"
OS_VERSION="$(docker run -it --rm "ubuntu:${TAG}" /bin/bash -c "grep VERSION_ID= /etc/os-release | cut -d= -f2 | sed -E 's/\"//g'" | tr -d "\r")"

if [ -n "${OS_VERSION}" ]; then
    echo "Found Ubuntu version '${OS_VERSION}'"
else
    echo "ERROR: Unable to determine Ubuntu version"
    exit 1
fi

# Generate tags
docker tag "${DOCKER_REPO}:ubuntu-${TAG}" "${DOCKER_USERNAME}/${DOCKER_REPO}:ubuntu-${TAG}"
docker tag "${DOCKER_REPO}:ubuntu-${TAG}" "${DOCKER_USERNAME}/${DOCKER_REPO}:ubuntu-${OS_VERSION}"

# Login to Docker Hub
echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

# Push the image and tags
docker push "${DOCKER_USERNAME}/${DOCKER_REPO}:ubuntu-${TAG}"
docker push "${DOCKER_USERNAME}/${DOCKER_REPO}:ubuntu-${OS_VERSION}"

# Push ubuntu-groovy as latest
if [ "${TAG}" == "groovy" ]; then
    docker tag "${DOCKER_REPO}:ubuntu-${TAG}" "${DOCKER_USERNAME}/${DOCKER_REPO}:latest"
    docker push "${DOCKER_USERNAME}/${DOCKER_REPO}:latest"
fi
